"""add validation_flags and validation_issues to applications

Revision ID: 35e920338458
Revises: 9c1315902377
Create Date: 2026-08-06 12:16:51.063205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35e920338458'
down_revision: Union[str, Sequence[str], None] = '9c1315902377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.alter_column('application_status_history', 'old_status',
               existing_type=postgresql.ENUM('STARTED', 'SUBMITTED', 'DOCS_PENDING', 'DOCS_VALIDATED', 'DOCS_INVALID', 'OFFER_MADE', 'OFFER_ACCEPTED', 'OFFER_REJECTED', 'OFFER_EXPIRED', 'WAITLISTED', 'REJECTED', name='application_status'),
               nullable=False)
    op.add_column('applications', sa.Column('validation_flags', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('validation_issues', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('storage_key', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('content_type', sa.String(length=150), nullable=False))
    op.add_column('documents', sa.Column('file_size_bytes', sa.Integer(), nullable=False))
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('documents', 'file_size_bytes')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'storage_key')
    op.drop_column('applications', 'validation_issues')
    op.drop_column('applications', 'validation_flags')
    op.alter_column('application_status_history', 'old_status',
               existing_type=postgresql.ENUM('STARTED', 'SUBMITTED', 'DOCS_PENDING', 'DOCS_VALIDATED', 'DOCS_INVALID', 'OFFER_MADE', 'OFFER_ACCEPTED', 'OFFER_REJECTED', 'OFFER_EXPIRED', 'WAITLISTED', 'REJECTED', name='application_status'),
               nullable=True)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
