"""make old_status nullable on application_status_history

Revision ID: 69ca23eb0a26
Revises: 35e920338458
Create Date: 2026-08-06 12:27:26.132913

"""

from collections.abc import Sequence

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69ca23eb0a26"
down_revision: str | Sequence[str] | None = "35e920338458"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "application_status_history",
        "old_status",
        existing_type=postgresql.ENUM(
            "STARTED",
            "SUBMITTED",
            "DOCS_PENDING",
            "DOCS_VALIDATED",
            "DOCS_INVALID",
            "OFFER_MADE",
            "OFFER_ACCEPTED",
            "OFFER_REJECTED",
            "OFFER_EXPIRED",
            "WAITLISTED",
            "REJECTED",
            name="application_status",
        ),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "application_status_history",
        "old_status",
        existing_type=postgresql.ENUM(
            "STARTED",
            "SUBMITTED",
            "DOCS_PENDING",
            "DOCS_VALIDATED",
            "DOCS_INVALID",
            "OFFER_MADE",
            "OFFER_ACCEPTED",
            "OFFER_REJECTED",
            "OFFER_EXPIRED",
            "WAITLISTED",
            "REJECTED",
            name="application_status",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
