"""add extracted income column in Loan Application table

Revision ID: abdcbe10440d
Revises: ba36f5c96a0b
Create Date: 2026-08-08 20:27:39.736179

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abdcbe10440d"
down_revision: str | Sequence[str] | None = "ba36f5c96a0b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playing_with_neon")
    op.add_column(
        "loan_applications",
        sa.Column("extracted_annual_income", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("loan_applications", "extracted_annual_income")
    op.create_table(
        "playing_with_neon",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("value", sa.REAL(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("playing_with_neon_pkey")),
    )
    # ### end Alembic commands ###
