"""added ALL_DOCS_UPLOADED status to ApplicationStatus enum

Revision ID: ba36f5c96a0b
Revises: d31547e9ffed
Create Date: 2026-08-08 09:42:34.622044

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba36f5c96a0b"
down_revision: str | Sequence[str] | None = "d31547e9ffed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE application_status ADD VALUE 'ALL_DOCS_UPLOADED'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
