"""added ALL_DOCS_UPLOADED status to ApplicationStatus enum

Revision ID: ba36f5c96a0b
Revises: d31547e9ffed
Create Date: 2026-08-08 09:42:34.622044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba36f5c96a0b'
down_revision: Union[str, Sequence[str], None] = 'd31547e9ffed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE application_status ADD VALUE 'ALL_DOCS_UPLOADED'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
