"""add marks column to student

Revision ID: cf022ca7a972
Revises: 48c2cbe4ba06
Create Date: 2026-08-07 10:55:45.161324

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf022ca7a972"
down_revision: str | Sequence[str] | None = "48c2cbe4ba06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("marks_physics", sa.Float(), nullable=True))
    op.add_column("students", sa.Column("marks_chemistry", sa.Float(), nullable=True))
    op.add_column("students", sa.Column("marks_maths", sa.Float(), nullable=True))
    op.add_column("students", sa.Column("marks_english", sa.Float(), nullable=True))
    op.add_column("students", sa.Column("total_marks", sa.Float(), nullable=True))
    op.add_column("students", sa.Column("marks_percentage", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "marks_percentage")
    op.drop_column("students", "total_marks")
    op.drop_column("students", "marks_english")
    op.drop_column("students", "marks_maths")
    op.drop_column("students", "marks_chemistry")
    op.drop_column("students", "marks_physics")
    # ### end Alembic commands ###
