"""added cs marks column in student

Revision ID: d31547e9ffed
Revises: 52bcb77c5e62
Create Date: 2026-08-08 09:19:59.879579

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d31547e9ffed"
down_revision: str | Sequence[str] | None = "52bcb77c5e62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students", sa.Column("marks_computer_science", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "marks_computer_science")
    # ### end Alembic commands ###
